SELECT ID,
    CASE
        WHEN PERCENT <= 0.25 THEN 'CRITICAL'
        WHEN 0.25 < PERCENT AND PERCENT <= 0.5 THEN 'HIGH'
        WHEN 0.5 < PERCENT AND PERCENT <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS 'COLONY_NAME'
FROM (
    SELECT *, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS 'PERCENT'
    FROM ECOLI_DATA
) e
ORDER BY ID;