SELECT ID,
       CASE PERCENT
           WHEN 1 THEN 'CRITICAL'
           WHEN 2 THEN 'HIGH'
           WHEN 3 THEN 'MEDIUM'
           WHEN 4 THEN 'LOW'
       END AS 'COLONY_NAME'
FROM (
    SELECT *, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
    FROM ECOLI_DATA
) AS e
ORDER BY ID;