SELECT ID, GENOTYPE, PARENT_GENOTYPE
FROM (
    SELECT *, (
        SELECT GENOTYPE
        FROM ECOLI_DATA b 
        WHERE a.PARENT_ID = b.ID) AS 'PARENT_GENOTYPE' 
    FROM ECOLI_DATA a
) e
WHERE PARENT_GENOTYPE & GENOTYPE = PARENT_GENOTYPE
ORDER BY ID;