SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E 
    INNER JOIN (
        SELECT EMP_NO, SCORE, RANK() OVER(ORDER BY SCORE DESC) AS RNK
        FROM (SELECT EMP_NO, SUM(SCORE) AS SCORE
              FROM HR_GRADE
              WHERE YEAR = '2022'
              GROUP BY EMP_NO
        ) AS S
    ) G ON E.EMP_NO = G.EMP_NO
WHERE RNK = 1;